# Configuración Jekyll para JesusCorner - Base Configuration
title: "JesusCorner - Recomendaciones Tech"
description: "Recomendaciones honestas de tecnología con las mejores ofertas"
# URL and baseurl are set in environment-specific config files

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections para organizar contenido
collections:
  reviews:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  products:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "review"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Site settings
author: "JesusCorner"
email: "contact@jesuscorner.com"
twitter_username: jesuscorner
github_username: jesuscorner

# Amazon settings
amazon_associate_id: "jesuscorner-21"

# Base exclusions (extended by environment configs)
# Environment-specific exclusions are defined in _config_dev.yml and _config_prod.yml
